root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "/$(go env GOPATH)/bin/dlv exec ./tmp/main --headless --listen=:2345 --api-version=2 --accept-multiclient --continue"
  cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ./cmd/web"
  include_ext = ["go", "html"]
  exclude_dir = ["node_modules", "data", "public", "tmp", ".vscode", "scripts", "styles"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true